"""Add suggested events support with metadata

Revision ID: 6dde2fa7c832
Revises: 411f52f8f873
Create Date: 2025-09-01 07:15:39.535463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dde2fa7c832'
down_revision: Union[str, Sequence[str], None] = '411f52f8f873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('suggestion_reason', sa.Text(), nullable=True))
    op.add_column('calendar_events', sa.Column('suggestion_confidence', sa.Integer(), nullable=True))
    op.add_column('calendar_events', sa.Column('user_feedback', sa.Text(), nullable=True))
    op.add_column('calendar_events', sa.Column('suggested_by', sa.String(length=100), nullable=True))
    op.add_column('calendar_events', sa.Column('parent_event_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_calendar_events_parent_event_id'), 'calendar_events', ['parent_event_id'], unique=False)
    op.create_foreign_key(None, 'calendar_events', 'calendar_events', ['parent_event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.drop_index(op.f('ix_calendar_events_parent_event_id'), table_name='calendar_events')
    op.drop_column('calendar_events', 'parent_event_id')
    op.drop_column('calendar_events', 'suggested_by')
    op.drop_column('calendar_events', 'user_feedback')
    op.drop_column('calendar_events', 'suggestion_confidence')
    op.drop_column('calendar_events', 'suggestion_reason')
    # ### end Alembic commands ###
